### ISSUE TITLE
differ does not detect changes between 2 catalogs

### ISSUE THREAD

**Issue by akosiaris** [acidprime/puppet-catalog-diff#48]
We 've been using at WMF this software for quite a long time and are quite happy with it. But we occasionally stumble across a case were 2 catalogs clearly differ but the software reports they are not. 

An example of that case is here:

https://puppet-compiler.wmflabs.org/5076/mw2152.codfw.wmnet/

where the production and the change catalog diff (e.g. search for the `freeipmi-tools` package in the change catalog) but the `puppet catalog diff` command does not report that (or other changes)

**Comment by KlavsKlavsen** [comment]
your links all show 404.. and what exact command are you using to run the diff?

**Comment by akosiaris** [comment]
After a year plus, they have expired. We have also migrated to a different diff solution in the process so this is no longer applicable for us. I 'll close as invalid
